#!/usr/bin/env bash
# ============================================================================
# Smart deploy for NarrativeHealth (idempotent — only does what changed).
#
#   git up        → 1. pull code (skip everything when already up to date)
#   2. install deps only when package.json / lockfile changed
#      (+ python deps only when backend/requirements*.txt changed)
#   3. run raw-SQL migrations only when drizzle/migrations changed
#   4. rebuild Next only when source/config/deps/migrations changed
#   5. pm2 restart — nextjs-dashboard after a build; fastapi-backend after
#      backend python changes; both after a full pull
#
# Usage:
#   bash scripts/deploy.sh           # full smart run
#   bash scripts/deploy.sh --force   # ignore markers, do everything
# ============================================================================
set -uo pipefail
cd "$(dirname "$0")/.."

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"
STATE_DIR=".deploy-state"
mkdir -p "$STATE_DIR"
MARK="$STATE_DIR/last-deploy.env"

# pm2 process names (must match `pm2 list` on the server)
PM2_NEXT="nextjs-dashboard"
PM2_PY="fastapi-backend"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

log()  { printf '\033[1;36m[deploy]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[  ok  ]\033[0m %s\n' "$*"; }
skip() { printf '\033[2m[ skip ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[ warn ]\033[0m %s\n' "$*"; }

pm2_restart() {
  local name="$1"
  if ! command -v pm2 >/dev/null 2>&1; then
    warn "pm2 not installed — start/reload manually"
    return 1
  fi
  if pm2 describe "$name" >/dev/null 2>&1; then
    if pm2 restart "$name" --update-env >/dev/null; then
      ok "pm2: $name restarted"
      return 0
    fi
    warn "pm2 restart $name failed"
    return 1
  fi
  warn "pm2 process '$name' not found — check 'pm2 list'"
  return 1
}

# ─── Load previous state ────────────────────────────────────────────────────
PREV_LOCK=""; PREV_MIG=""; PREV_SRC=""; PREV_PY=""; PREV_PY_HASH=""
# STALE-GUARD: a build whose pm2 restart failed (or was skipped because pm2
# was momentarily unavailable) must NOT be forgotten — retry the restart on
# the very next run, even when nothing else changed.
PENDING_NEXT_RESTART=0
PENDING_PY_RESTART=0
if [[ -f "$STATE_DIR/pending-restarts" ]]; then
  source "$STATE_DIR/pending-restarts"
fi
if [[ -f "$MARK" && $FORCE -eq 0 ]]; then
  # shellcheck disable=SC1090
  source "$MARK"
fi

STARTED=$(date +%s)
log "Smart deploy — branch: $BRANCH"

# ─── 1. Code: pull only if there is something new ───────────────────────────
git fetch origin "$BRANCH" --quiet 2>/dev/null
LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse "origin/$BRANCH" 2>/dev/null || echo "$LOCAL")

NEED_BUILD=0; NEED_DEPS=0; NEED_MIG=0; PULLED=0; PY_CHANGED=0

if [[ "$LOCAL" != "$REMOTE" ]]; then
  AHEAD=$(git rev-list --count "origin/$BRANCH..HEAD" 2>/dev/null || echo 0)
  if [[ "$AHEAD" -gt 0 ]]; then
    warn "local has $AHEAD unpushed commit(s) — pulling may conflict; continuing"
  fi
  # next-env.d.ts is regenerated by next dev/build; drop local noise so pull
  # never aborts with "local changes would be overwritten".
  git checkout -- next-env.d.ts 2>/dev/null || true
  if git pull --ff-only origin "$BRANCH"; then
    PULLED=1
    ok "code updated: $(git rev-parse --short HEAD)"
  else
    warn "fast-forward failed — resolve manually, continuing with current code"
  fi
else
  skip "code already up to date ($(git rev-parse --short HEAD))"
fi

# ─── 2a. Node dependencies: install only when lockfile inputs changed ───────
LOCK_HASH=$(cat package.json package-lock.json bun.lock 2>/dev/null | sha256sum | cut -d' ' -f1)
if [[ $FORCE -eq 1 || "$LOCK_HASH" != "$PREV_LOCK" ]]; then
  log "installing node dependencies…"
  if command -v bun >/dev/null 2>&1 && [[ -f bun.lock ]]; then
    bun install --frozen-lockfile || npm install
  else
    npm install
  fi
  ok "node dependencies ready"
else
  skip "node dependencies unchanged"
fi

# ─── 2b. Python dependencies: install only when backend requirements changed
REQ_HASH=$(cat backend/requirements*.txt 2>/dev/null | sha256sum | cut -d' ' -f1)
if [[ $FORCE -eq 1 || "$REQ_HASH" != "$PREV_PY" ]]; then
  if [[ -n "$(ls backend/requirements*.txt 2>/dev/null)" ]]; then
    log "installing python dependencies…"
    if [[ -x ".venv/bin/pip" ]]; then
      .venv/bin/pip install -q -r backend/requirements.txt && ok "python deps (venv)"
      PYDEPS_RAN=1
    elif command -v pip3 >/dev/null 2>&1; then
      pip3 install -q --user -r backend/requirements.txt && ok "python deps (--user)"
      PYDEPS_RAN=1
    else
      warn "pip not found — skipped python deps"
    fi
  fi
fi

# ─── 3. Migrations: run only when drizzle/migrations changed ────────────────
# scripts/migrate-raw.ts applies every drizzle/migrations/*.sql through the pg
# driver (no psql needed), records sha256 per file in _raw_migrations, and is
# idempotent end-to-end. It replaces `drizzle-kit migrate`, which requires the
# meta/_journal.json state this repo's DB never had (schema was built via
# db:push), and fails without psql on bare VPSes.
MIG_HASH=$(find drizzle/migrations -name '*.sql' -type f 2>/dev/null | sort | xargs sha256sum 2>/dev/null | sha256sum | cut -d' ' -f1)
if [[ $FORCE -eq 1 || "$MIG_HASH" != "$PREV_MIG" ]]; then
  log "applying migrations (raw SQL runner, idempotent)…"
  if npx tsx scripts/migrate-raw.ts || bun scripts/migrate-raw.ts; then
    ok "migrations applied"
    NEED_MIG=1
  else
    warn "migration runner FAILED - will retry on next deploy (marker not updated)"
    # Keep the old hash so the next deploy re-runs the migration step instead
    # of wrongly skipping it.
    MIG_HASH="$PREV_MIG"
  fi
else
  skip "migrations unchanged"
fi

# ─── 4. Build: only when source / config / deps / migrations changed ───────
SRC_HASH=$( (git rev-parse HEAD; find src next.config.ts drizzle.config.ts tsconfig.json package.json -type f 2>/dev/null | sort | xargs sha256sum 2>/dev/null) | sha256sum | cut -d' ' -f1 )
if [[ $FORCE -eq 1 || "$SRC_HASH" != "$PREV_SRC" ]]; then
  log "building Next.js (cpus capped — safe on small VPS)…"
  npm run build || { warn "build FAILED — keeping previous .next"; exit 1; }
  ok "build completed"
  NEED_BUILD=1
else
  skip "build unchanged — reusing existing .next"
fi

# ─── 5. pm2 restarts — only what actually changed ───────────────────────────
# backend python sources changed? (backend/ excluding caches/logs)
PY_HASH=$(find backend -name '*.py' -not -path '*__pycache__*' 2>/dev/null | sort | xargs sha256sum 2>/dev/null | sha256sum | cut -d' ' -f1)
if [[ $FORCE -eq 1 || "$PY_HASH" != "$PREV_PY_HASH" ]]; then
  PY_CHANGED=1
fi

NEXT_RESTART_OK=1; PY_RESTART_OK=1
if [[ $NEED_BUILD -eq 1 || $PENDING_NEXT_RESTART -eq 1 ]]; then
  [[ $PENDING_NEXT_RESTART -eq 1 && $NEED_BUILD -eq 0 ]] && warn "retrying pending nextjs-dashboard restart from a previous run"
  pm2_restart "$PM2_NEXT" || NEXT_RESTART_OK=0
else
  skip "nextjs-dashboard restart not needed (no rebuild)"
fi

if [[ $PY_CHANGED -eq 1 || $PENDING_PY_RESTART -eq 1 ]]; then
  [[ $PENDING_PY_RESTART -eq 1 && $PY_CHANGED -eq 0 ]] && warn "retrying pending fastapi-backend restart from a previous run"
  pm2_restart "$PM2_PY" || PY_RESTART_OK=0
else
  skip "fastapi-backend restart not needed (no python change)"
fi

# Persist pending-restart flags when a required restart did not succeed.
if [[ $NEXT_RESTART_OK -eq 1 && $PY_RESTART_OK -eq 1 ]]; then
  rm -f "$STATE_DIR/pending-restarts"
else
  cat > "$STATE_DIR/pending-restarts" <<EOF
PENDING_NEXT_RESTART=$(( 1 - NEXT_RESTART_OK ))
PENDING_PY_RESTART=$(( 1 - PY_RESTART_OK ))
EOF
  warn "some pm2 restarts did not succeed — they will retry on the next 'git up'"
fi

# ─── Persist state ──────────────────────────────────────────────────────────
cat > "$MARK" <<EOF
PREV_COMMIT=$(git rev-parse --short HEAD)
PREV_LOCK=$LOCK_HASH
PREV_MIG=$MIG_HASH
PREV_SRC=$SRC_HASH
PREV_PY_HASH=$PY_HASH
LAST_RUN=$(date -Iseconds)
EOF

DUR=$(( $(date +%s) - STARTED ))
log "done in ${DUR}s — (code:$PULLED deps:$NEED_DEPS mig:$NEED_MIG build:$NEED_BUILD pyRestart:$PY_CHANGED)"
