#!/usr/bin/env bash
# ============================================================================
# Smart deploy for NarrativeHealth (idempotent — only does what changed).
#
#   git up        → 1. pull code (skip everything when already up to date)
#   2. install deps only when package.json / lockfile changed
#   3. run drizzle migrations only when drizzle/migrations changed
#      (idempotent SQL files: CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT
#      EXISTS — safe to re-run the whole set; state tracked by marker hash)
#   4. rebuild Next only when source/config/deps/migrations changed
#   5. pm2 restart only when a build actually happened
#
# Usage:
#   bash scripts/deploy.sh           # full smart run
#   bash scripts/deploy.sh --force   # ignore markers, do everything
# ============================================================================
set -uo pipefail
cd "$(dirname "$0")/.."

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"
STATE_DIR=".deploy-state"
mkdir -p "$STATE_DIR"
MARK="$STATE_DIR/last-deploy.env"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

log()  { printf '\033[1;36m[deploy]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[  ok  ]\033[0m %s\n' "$*"; }
skip() { printf '\033[2m[ skip ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[ warn ]\033[0m %s\n' "$*"; }

# ─── Load previous state ────────────────────────────────────────────────────
PREV_COMMIT=""; PREV_LOCK=""; PREV_MIG=""; PREV_SRC=""
if [[ -f "$MARK" && $FORCE -eq 0 ]]; then
  # shellcheck disable=SC1090
  source "$MARK"
fi

STARTED=$(date +%s)
log "Smart deploy — branch: $BRANCH"

# ─── 1. Code: pull only if there is something new ───────────────────────────
git fetch origin "$BRANCH" --quiet 2>/dev/null
LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse "origin/$BRANCH" 2>/dev/null || echo "$LOCAL")

NEED_BUILD=0; NEED_DEPS=0; NEED_MIG=0; PULLED=0

if [[ "$LOCAL" != "$REMOTE" ]]; then
  AHEAD=$(git rev-list --count "origin/$BRANCH..HEAD" 2>/dev/null || echo 0)
  if [[ "$AHEAD" -gt 0 ]]; then
    warn "local has $AHEAD unpushed commit(s) — pulling may conflict; continuing"
  fi
  # next-env.d.ts is regenerated by next dev/build; drop local noise so pull
  # never aborts with "local changes would be overwritten".
  git checkout -- next-env.d.ts 2>/dev/null || true
  if git pull --ff-only origin "$BRANCH"; then
    PULLED=1
    ok "code updated: $(git rev-parse --short HEAD)"
  else
    warn "fast-forward failed — resolve manually, continuing with current code"
  fi
else
  skip "code already up to date ($(git rev-parse --short HEAD))"
fi

# ─── 2. Dependencies: install only when the lockfile inputs changed ────────
LOCK_HASH=$(cat package.json package-lock.json bun.lock 2>/dev/null | sha256sum | cut -d' ' -f1)
if [[ $FORCE -eq 1 || "$LOCK_HASH" != "$PREV_LOCK" ]]; then
  log "installing dependencies…"
  if command -v bun >/dev/null 2>&1 && [[ -f bun.lock ]]; then
    bun install --frozen-lockfile || npm ci
  elif [[ -f package-lock.json ]]; then
    npm ci
  else
    npm install
  fi
  ok "dependencies ready"
  NEED_DEPS=1
else
  skip "dependencies unchanged"
fi

# ─── 3. Migrations: run only when drizzle/migrations changed ────────────────
# scripts/migrate-raw.ts applies every drizzle/migrations/*.sql through the pg
# driver (no psql needed), records sha256 per file in _raw_migrations, and is
# idempotent end-to-end. It replaces `drizzle-kit migrate`, which requires the
# meta/_journal.json state this repo's DB never had (schema was built via
# db:push), and fails without psql on bare VPSes.
MIG_HASH=$(find drizzle/migrations -name '*.sql' -type f 2>/dev/null | sort | xargs sha256sum 2>/dev/null | sha256sum | cut -d' ' -f1)
if [[ $FORCE -eq 1 || "$MIG_HASH" != "$PREV_MIG" ]]; then
  log "applying migrations (raw SQL runner, idempotent)…"
  if npx tsx scripts/migrate-raw.ts || bun scripts/migrate-raw.ts; then
    ok "migrations applied"
  else
    warn "migration runner failed — check DATABASE_URL / connectivity"
  fi
  NEED_MIG=1
else
  skip "migrations unchanged"
fi

# ─── 4. Build: only when source / config / deps / migrations changed ───────
SRC_HASH=$( (git rev-parse HEAD; find src next.config.ts drizzle.config.ts tsconfig.json package.json -type f 2>/dev/null | sort | xargs sha256sum 2>/dev/null) | sha256sum | cut -d' ' -f1 )
if [[ $FORCE -eq 1 || "$SRC_HASH" != "$PREV_SRC" ]]; then
  log "building Next.js (cpus capped — safe on small VPS)…"
  npm run build || { warn "build FAILED — keeping previous .next"; exit 1; }
  ok "build completed"
  NEED_BUILD=1
else
  skip "build unchanged — reusing existing .next"
fi

# ─── 5. Restart pm2: only after a fresh build ───────────────────────────────
if [[ $NEED_BUILD -eq 1 ]]; then
  if command -v pm2 >/dev/null 2>&1; then
    if pm2 describe narrative-health >/dev/null 2>&1; then
      pm2 restart narrative-health --update-env && ok "pm2: narrative-health restarted"
    else
      warn "pm2 process 'narrative-health' not found — start it once manually:"
      warn "  pm2 start npm --name narrative-health -- run start"
      warn "then re-run this script to get auto-restarts."
    fi
  else
    warn "pm2 not installed — start/reload manually (npm run start)"
  fi
else
  skip "server restart not needed"
fi

# ─── Persist state ──────────────────────────────────────────────────────────
cat > "$MARK" <<EOF
PREV_COMMIT=$(git rev-parse --short HEAD)
PREV_LOCK=$LOCK_HASH
PREV_MIG=$MIG_HASH
PREV_SRC=$SRC_HASH
LAST_RUN=$(date -Iseconds)
EOF

DUR=$(( $(date +%s) - STARTED ))
log "done in ${DUR}s — (code:$PULLED deps:$NEED_DEPS mig:$NEED_MIG build:$NEED_BUILD)"
